# Generated by Django 5.2.8 on 2025-11-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0009_order_cancellation_reason_order_cancelled_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="current_usage",
        ),
        migrations.RemoveField(
            model_name="order",
            name="cancellation_reason",
        ),
        migrations.RemoveField(
            model_name="order",
            name="cancelled_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="coupon_discount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_notes",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_phone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="discount_code_used",
        ),
        migrations.RemoveField(
            model_name="order",
            name="first_time_discount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_value_discount",
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="bookstore.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderCancellation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation",
                        to="bookstore.order",
                    ),
                ),
            ],
        ),
    ]
