# Generated by Django 5.2.8 on 2025-11-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0010_remove_coupon_current_usage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="order",
            name="first_time_discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="order",
            name="order_value_discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
