# Generated by Django 5.2.8 on 2025-11-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0013_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Confirmed",
                max_length=20,
            ),
        ),
    ]
